### ISSUE TITLE
Please add options to configure colors of legend text and axis text.

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [apexcharts/apexcharts.js#1004]
I am using the bar chart on a dark background, out of the box, legend and axis text colors are white which dont show on dark background.

Add options to configure these text colors

I am currently overriding `apexcharts-legend-text` & `apexcharts-yaxis-title-text`. Also adding a 'cssClass' option for xaxis which doesnt get reflected in exported png files.

**Comment by junedchhipa** [comment]
Take a look at this dark dashboard to see how the text colors can be applied globally
https://apexcharts.com/javascript-chart-demos/dashboards/dark/
Code: https://github.com/apexcharts/apexcharts.js/tree/master/samples/vanilla-js/dashboards/dark

Setting global chart's color
```javascript
var options = {
  chart: {
    foreColor: '#fff'
  }
}
```

This will apply the same foreColor to axis texts and legend.

Regarding the CSS classes not being applied in exported png files, it is a limitation due to styles not presented inside the chart scope while exporting.

**Comment by dfiorini** [comment]
I'm searching too to change color of legend, but it remain the same color of Options.Colors, did you resolve it ?

**Comment by cosmicknox** [comment]
same issue  here want to change the label text to white for pie chart but cant seem to find it tried doing all the css but still no reflections . these 2 are the only css that works for me till now

`.apexcharts-legend-series {
    cursor: pointer;
    line-height: normal;
    display: flex;
    align-items: center;
}
.apexcharts-tooltip span {
    color: #ffffff;
}`
