### ISSUE TITLE
Annotations not showing up in chart context

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#1021]
I'm adding annotations using ApexCharts.exec(chartId, 'addXaxisAnnotation', params) in the chart.events.click function.

I also check if there is an existing annotations using context.config.annotations.xaxis

However, the annotations I'm adding are not showing up here.

How can we access the current annotations from the click event?

**Comment by ThinkSalat** [comment]
@junedchhipa Any idea why this would happen/how to access current annotations from the click event?

**Comment by strixy** [comment]
I believe this issue was introduced in v3.11 as rolling back to v3.10 works as expected. Issue remains in v3.15.

I wonder if this is a z-index / layer order issue as the context on click appears to be the chart canvas proper (classList shows apexcharts-canvas and inspect element can't select the pin, but rather the chart canvas). I have tried adding `position: 'front'` to the annotations config, but to no effect. I am running with a custom SVG annotation, but as noted that worked in v3.10 without issue though this fact may be a contributing issue.

**Comment by junedchhipa** [comment]
Without a codepen, I am unable to visualize easily what is the exact issue.
Please create a codepen demo so I can reproduce on my side.

**Comment by strixy** [comment]
Bah. That'll take too long. PR incoming. What I need to know before I commit this fix is if the x and y axis annotations are also meant to be clickable (currently disabled as well if so). I don't use them so some input is required and also greatly appreciated! Thanks in advance.

**Comment by strixy** [comment]
I looked through the docs a little and couldn't find anything directly related to clicking (or any mouse event) on the x and y annotations, but I couldn't find anything that suggested it should be prevented either. I've returned mouse events to all three.
