### ISSUE TITLE
Extend custom tooltip example with more values

### ISSUE THREAD

**Issue by Simpleqode** [apexcharts/apexcharts.js#1176]
Apex Charts tooltips are very powerful and I like that we can customize them with the `Apex.tooltip.custom` method. A regular Apex Charts tooltip contains lots of information in it, however in the custom tooltip example you have (https://codepen.io/apexcharts/pen/NBdyvV) you only show how to get the current value which is the easiest to find. I tried to find the category names but the `w` object is so huge it's very hard to find the info you need there. It would be great if you could extent the custom tooltip example with all the info you have in the regular tooltip.

**Comment by junedchhipa** [comment]
Sure, I will update the example.

**Comment by junedchhipa** [comment]
Updated the codepen.
X-values or categories are accessible in `w.globals.labels`

```javascript
tooltip: {
  custom: function({ series, seriesIndex, dataPointIndex, w }) {
    return (
      '<div class="arrow_box">' +
      '<span>' +
      w.globals.labels[dataPointIndex] +
      ': ' +
      series[seriesIndex][dataPointIndex] +
      '</span>' +
      '</div>'
    )
  }
}
```

**Comment by Simpleqode** [comment]
Thanks for that. Problem with this approach is that when you switch to line charts, category names will be presented as numbers: https://codepen.io/Deka87/pen/YzPExYx?editors=0010. Any workaround for this?

**Comment by ederson13** [comment]
i had the same issue 
use categoryLabels instead of labels

**Comment by wkasbar** [comment]
Hi there! First of all I want to say that ApexCharts is amazing and allow you make so great things custom.  

In this case i have some issues for my custom tooltip...
I'm trying to add an arrow at the bottom of the tooltip, but the problem is that I can't center the tooltip when I mouse over the series data on the right side of the chart... Can you help me please.

I know other graphing tools use the property yAling:bottom.

By the way I'm applying ApexCharts  "apexcharts": "^3.35.5", "react-apexcharts": "^1.4.0" with React.js. 

Finally i can't apply the mode and behavior:  
    highlightingMode="FadeOthersSpecific"
    highlightingBehavior="NearestItemsAndSeries"

Thanks in advance for all the support you can give me.

![Captura de pantalla de 2022-09-15 11-53-39](https://user-images.githubusercontent.com/106111324/190437526-ba37dfc1-14ed-4a8e-b0f0-c07006a6f14a.png)

![Captura de pantalla de 2022-09-15 11-53-28](https://user-images.githubusercontent.com/106111324/190437659-a7d97b5c-b629-49da-953e-04515ab2660c.png)

![Captura de pantalla de 2022-09-15 11-51-17](https://user-images.githubusercontent.com/106111324/190437746-cf11385c-e512-43e7-96e1-78a69919b5c2.png)

![Captura de pantalla de 2022-09-15 11-50-44](https://user-images.githubusercontent.com/106111324/190437782-48cdda56-a52b-4535-9be2-f6e55dd3c9b8.png)

![Captura de pantalla de 2022-09-15 11-52-47](https://user-images.githubusercontent.com/106111324/190437851-eb5dbbb9-609f-4f08-8b3a-992081d06d38.png)

![Captura de pantalla de 2022-09-15 11-53-02](https://user-images.githubusercontent.com/106111324/190437894-1df87a1e-acfc-4bc4-a0d1-ea6550e6a14f.png)

**Comment by shahhhashmatali2002** [comment]
tooltip: {
        theme: 'light',
        x: {
          show: false,
        },
        custom: function ({ series, seriesIndex, dataPointIndex, w }: any) {
          const month = w.globals.labels[dataPointIndex];
          const value = series[seriesIndex][dataPointIndex];
          const color = w.globals.colors[dataPointIndex];
          const circleColor = w.globals.stroke.colors[seriesIndex]; // Use stroke color for the circle

          return (
            '<div class="arrow_box">' +
            '<div class="circle" style="background-color: ' + color + ';"></div>' +
            "<span>" +
            month +
            ": " +
            value.toFixed(2) +
            "%</span>" +
            "</div>"
          );
        }
      }
      
      // css
      .arrow_box {
  position: relative;
  background: #fff;
  /* border: 2px solid #000000; */
  margin: 5px 10px 5px 10px;
  display: flex;
  align-items: center;
}
.arrow_box:after, .arrow_box:before {
  right: 100%;
  top: 50%;
  border: solid transparent;
  content: " ";
  height: 0;
  width: 0;
  position: absolute;
  pointer-events: none;
}

.arrow_box:after {
  border-color: rgba(85, 85, 85, 0);
  /* border-right-color: #555; */
  /* border-width: 10px; */
  margin-top: -10px;
}
.arrow_box:before {
  border-color: rgba(0, 0, 0, 0);
  /* border-right-color: #000000; */
  /* border-width: 13px; */
  margin-top: -13px;
}

.circle {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  margin-right: 8px;
}
