### ISSUE TITLE
Is it possible to have the pie/donut automatically scale to its containers width?

### ISSUE THREAD

**Issue by Robinwist** [apexcharts/apexcharts.js#1227]
Setting the width in the chart settings to e.g 500 doesn't actually make the donut itself 500px wide. It always leaves some padding between itself and its container (which _is_ 500px wide) which seems to be calculated somewhere I can't quite put my finger on.
All legends, extra clutter etc are removed so it's just the actual pie/donut within its container.

Example:
![Schermafbeelding 2020-01-17 om 11 52 33](https://user-images.githubusercontent.com/9716965/72606955-e7908900-391f-11ea-8070-6c130e23dc47.png)

Maybe add a possible option/setting where the pie/donut actually scales to the available width and not leave some form of padding between itself and the container edges.

If this isn't a possibility, then maybe you could enlighten me about the calculations behind the actual width so I can calculate this myself.

Thanks in advance!

**Comment by junedchhipa** [comment]
I noticed there is some hardcoded padding for pie/donut charts.
I will remove it.

Once that is done and released, try
```javascript
chart: {
  height: '100%'
}
```
to allow the pie/donut to take up full space.

**Comment by oherik** [comment]
I think the issue is still present in v3.15.3. @Robinwist, did the latest version fix it for your part?

I'm afraid I can't show you a Codepen, since the CDN is still at v3.15.2, but this is how it looks at my end:

```html
 <apexchart
      height="100%"
      width="100%"
      :options="chartOptions"
      :series="[75, 25]"
      class="chart-wrapper"
    ></apexchart>
```

```ts
chartOptions(): ApexOptions {
      return {
        chart: { type: "radialBar" },
        plotOptions: {
          radialBar: {
            startAngle: -90,
            endAngle: 90,
            dataLabels: {
              name: {
                show: false
              },
              value: {
                show: false
              }
            }
          }
        },
        tooltips: {
          enabled: false
        },
        legend: {
          show: false
        }
      };
    }
```

```scss 
.chart-wrapper {
  height: 400px;
  width: 600px;
  background: pink;
}
```
![image](https://user-images.githubusercontent.com/10709871/73465448-b46ae280-4380-11ea-86a0-15453c2e725a.png)

As you can see, the chart doesn't cover either 100% of the width or 100% of the height of the parent container. I would expect the chart to fill up the entire width or height of the parent container. Am I missing something?
