### ISSUE TITLE
toggleSeries/showSeries

### ISSUE THREAD

**Issue by arjhunAtcodingmart** [apexcharts/apexcharts.js#1286]
# Bug report

It seems that showSeries is not working fine for me, where I have used line chart with custom legend, hideSeries method is working fine, but when I use showSeries cannot able to show the line again in the chart, also tried the toggleSeries which is also hiding the line in chart not showing them again when toggling. And always returning false on toggleSeries

Using ApexChart.exec()

**Comment by arjhunAtcodingmart** [comment]
working fine with default legend, need help with this

**Comment by junedchhipa** [comment]
Which version of ApexCharts are you using? This problem was recently fixed.

**Comment by arjhunAtcodingmart** [comment]
Using
"apexcharts": "^3.15.2"
"react-apexcharts": "^1.3.6",

**Comment by juanr2001** [comment]
@junedchhipa I think I found a work-around. However, I am NOT 100% sure why the word-around even works.

So I ended up setting the legendClick to a function like:
```
apex.chart.events.legendClick = function (context, configs) {}
```

Maybe some modules that calls the legend's click function explicitly expects a type `function` to do something, instead of expecting `function` && `undefined`:
```
typeof legendClick === 'function'
```

Again, I am not sure. I haven't look at the source code, but I hope it helps.

By the way I am using:
```
"vue": "^2.6.11",
"apexcharts": "^3.15.5"
```

**Comment by arjhunAtcodingmart** [comment]
**@junedchhipa** Still not able to find any other way to toggle the charts with custom legends

**Comment by junedchhipa** [comment]
I just tried this example - https://github.com/apexcharts/apexcharts.js/blob/master/samples/vanilla-js/misc/custom-legend.html with `ApexCharts.exec(chartID, 'hideSeries', seriesName)` and it worked fine.

Can you please create a codepen / codesandbox demo so I can take a closer look?

**Comment by arjhunAtcodingmart** [comment]
Yeah, it's working fine. some component rendering issue, thanks for your time
