### ISSUE TITLE
Incorrect display of xaxis with HideOverlappingLabels=true

### ISSUE THREAD

**Issue by xjh666** [apexcharts/apexcharts.js#1290]
# Bug report

The display of xaxis labels with HideOverlappingLabels set as true is incorrect. 

## Codepen

https://codepen.io/xjh666/pen/vYOYmGz 

## Explanation

Some labels are hidden correctly, but some part are still crowded and cannot be seen clearly.

**Comment by junedchhipa** [comment]
Fixed in https://github.com/apexcharts/apexcharts.js/commit/85b4fcfbdfb4475141e3ed990c7f7af90ef9ab74

**Comment by frcfarias** [comment]
Hi,

I noticed in the very next commit https://github.com/apexcharts/apexcharts.js/commit/dcbd6ee2714413135fdfabcb31e0fd0948c633a0 on this file (AxesUtils.js) you undid the change to increase the overlaping labels threshold (currently on master). Is there any problem for you to update again from Math.abs(w.config.xaxis.labels.rotate) / 12 to Math.abs(w.config.xaxis.labels.rotate) / 20 or does it causes any incorrect behaviour?
Because we are still facing the same problem (its possible to check that on the same codepen provided in this issue). 

Thanks in advance!
