### ISSUE TITLE
Optimize CPU usage

### ISSUE THREAD

**Issue by thellimist** [apexcharts/apexcharts.js#1298]
I have read other issues written here. I want to see if there are other ways to optimize the graphs.

I know each graph is different. So, I'll put them here. I'm using mostly
1) Line Chart
2) Mix Line/Bar Chart
3) Area Chart
4) Bar Chart
5) Heatmap

with almost everything (except texts) default and with annotations

I have tried the following but it's still higher then I'd like. 

1) Disable animations
2) Marker size 

Is there any other optimization you recommend? 
Thanks

**Comment by junedchhipa** [comment]
Disabling animations, hiding markers, and data-labels are the ones that will significantly reduce the load. Annotations should also be kept to a small number (up to 20-30 will not hurt) as each annotation adds 3 DOM nodes.

In SVG charts, the less the DOM elements, the better the performance.

Here is the order of XY chart types from best to worst performance.

`Line` > `Area` > `Radar` > `Bar` > `Heatmap` > `Scatter/Bubble`

The reason is that the line chart has just 1 primary DOM element (path) covering all data-points while a scatter chart has a separate DOM element for each data-point.
