### ISSUE TITLE
Overlap Columns - Basic column chart

### ISSUE THREAD

**Issue by kylawamg** [apexcharts/apexcharts.js#1356]
Hi, 

Im trying to overlap the columns of each series but by default the chart draw each column in their own space. Is there any option to achieve this? 

I think, that, maybe, if I use stacked=true and play with the values of each serie I can achieve this effect but this workaround is not the best option...so could you help me?

Thanks in advance!!

**Comment by junedchhipa** [comment]
That's the standard behavior. Are you trying with a single series chart or multiple series?
Utmost care is taken to avoid overlapping bars, so I don't think it is possible to achieve what you desire.

**Comment by kylawamg** [comment]
I tried both options, multiple and single. Ok! I expected that, so I'll try to trick the values ​​to represent them that way.

Thanks you for your help!

**Comment by nikoaliro** [comment]
I am looking for this feature as well. Have you found a solution?

**Comment by RicardoGG20** [comment]
I have the same question, can you publish your solution?

**Comment by syn-nitin** [comment]
Even I am looking for overlapping bars (With a transparency in color) in a bar graph instead of multiple parallel bars. There are lots of use cases where this would be highly helpful, specially where we need to give a comparison on different data of same unit. Would like to see this as an in-built feature.
