### ISSUE TITLE
Heatmap Color Range - Single Series

### ISSUE THREAD

**Issue by Daniel4Digital** [apexcharts/apexcharts.js#1370]
**Is your feature request related to a problem? Please describe.**	
When I create an Heatmap with a single color (blue), when it renders the heatmap, all elements with 0 appears as pure white #FFF like my background, and therefore I dont see the borders/gaps between the elements

**Describe the solution you'd like**	
If we could add a color range between 2 colors, as a whitish blue and blue. Then the 0 will not appear as pure white but as a whitish blue. As we would be able to see the borders/gaps between elements

**Describe alternatives you've considered**	
I've tried to use the colorScale, using from and to = 0 but didnt work ofc. I tried to use the min value as 1, but there is no way afaik to do what I want with the features available.

**Additional context**	
As we can see in the img below, it looks bad since the background is white.
https://i.imgur.com/61PNaO0.png

**Comment by junedchhipa** [comment]
@Daniel4Digital The color scale for heatmap was broken which is just fixed in the last [commit](https://github.com/apexcharts/apexcharts.js/commit/4f59a79176e6813734c45430a9964238db8ac1cd#diff-0cf026bf0a13911aae7e53af760dd8b9)

So, with the next release, the below code should work fine (the screenshot attached is the result of the color scale).
```javascript
plotOptions: {
  heatmap: {
    colorScale: {
      ranges: [
        {
          from: 0,
          to: 2,
          color: '#00A100'
        }
      ]
    }
  }
}
```
![Screen Shot 2020-03-10 at 7 13 28 PM](https://user-images.githubusercontent.com/17950663/76318152-4c0a0c00-6303-11ea-8cd1-9585159cf9ba.png)
