### ISSUE TITLE
Thin columns

### ISSUE THREAD

**Issue by xxx44yyy** [apexcharts/apexcharts.js#1497]
# Bug report
![image](https://user-images.githubusercontent.com/40538167/79231188-5cffed00-7e6e-11ea-8759-4b39d5954bf0.png)

Why are the columns so thin? What's wrong?

## Codepen
https://codepen.io/xxx44yyy/pen/BaoodrG?editors=0010

**Comment by junedchhipa** [comment]
Because the minimum difference between some of the two values is very small as compared to the rest.
In your example, your last 2 x-values are very close (30 Nov 2019 and 31 Dec 2019)
While the chart starts somewhere in 2005.

If you remove the last value in your series array, you will notice the bars become thick.

Alternatively, you can increase the width manually (overlaps may occur)

```javascript
plotOptions: {
  bar: {
    columnWidth: '120%'
  }
}
```
