### ISSUE TITLE
Legend alignement and tooltip with synchronized charts

### ISSUE THREAD

**Issue by AxelBayle** [apexcharts/apexcharts.js#1728]
Hi,
I try to display 3 synchronized graphs but I'm facing two issues : 

## Explanation

- What is the behavior you expect?
  I want the 3 graphs be align, no matter the legend size & I wish to only show the tool tip of the active graph instead of all of them

- What is happening instead?

<img width="899" alt="Capture" src="https://user-images.githubusercontent.com/43752046/86254521-34a6a580-bbb6-11ea-9fc0-61e8a1255bd9.PNG">

**Comment by junedchhipa** [comment]
This is a known issue with synchronized charts and as of now, there is no easy fix for it.
Related to #1404.

In your case, you may change the legend's position and move it beneath the charts instead of left. This will make the inner width of all charts equal and synchronization will work as expected.

**Comment by AxelBayle** [comment]
Ok thanks you, and I have another question. I'd like to only have the tooltip on the graph I'm hovering instead of all of them do you know how can I do that ?

**Comment by KarlKrabb** [comment]
Hi @junedchhipa i am having the same issue as @AxelBayle in this ticket, i would like to have a dashboard view with charts in the same group that vary in width. have you found a solution for this yet?

@AxelBayle did you have any luck on a potential work around for this issue?
