### ISSUE TITLE
Error when showing markers on a series with a single element

### ISSUE THREAD

**Issue by jessecrossley** [apexcharts/apexcharts.js#1769]
A line series with a single value with showNullDataPoints: false will throw mouseover errors indicating that a circle should not have a negative radius. 
Error: <circle> attribute r: A negative value is not valid. ("-1")

See the highly-specific test harness [here](https://codesandbox.io/s/vue-apexcharts-synchronized-timelines-zp9h1?file=/src/components/Chart.component.vue)

See the error in the browser console [here](https://zp9h1.csb.app/)

**Comment by ChuckzM** [comment]
Was there a solution for this ?? I am getting the same type of error when the series has only one value but in my case it happens when showNullDataPoints = false or true. 

Error: <circle> attribute r: A negative value is not valid. ("-0.5")

This is the specific error, the rest of the series that have 0 or more than 1 values do not get this error.
