### ISSUE TITLE
Enabling slice expansion on hover

### ISSUE THREAD

**Issue by eliasdiek** [apexcharts/apexcharts.js#1862]
Hi,

Thank you for the great library. It's very useful for me.
We are using Pie/Donut Chart, I would like to ask you guys if there is a way to enable slice expansion on the hover event.
I can see there is a way to enable slice expansion on click event but seems not for hover event.
Please let me know if you have any solutions.
Thank you in advance!

**Comment by Mangor1no** [comment]
Is there any solution for this feature yet? Would love to see it in action

**Comment by DivyChauhan** [comment]
any updates or workaround with this?

**Comment by Neschadin** [comment]
[my solution =>](https://stackoverflow.com/a/78624946/20842610)

**Comment by sFarkhod** [comment]
@Neschadin Hello Mr Neschadin. The idea is pure genius, it's working perfectly.

**Comment by junedchhipa** [comment]
Both slice states have been reworked. Not quite as asked, so let me say what landed and why.

The request here was to expand a slice on hover, the way a click already did. We went a different way: expanding on hover meant borrowing the click's visual, which left hover and click saying the same thing, and the expansion itself was a re-draw at a larger radius, so an expanded slice silently claimed a bigger share than its value. Each state now gets its own visual, and neither is a recolour.

**Hover** traces a translucent band just outside the rim of the slice, in that slice's own colour, instead of lightening the fill. So a hovered slice keeps the colour the legend and the data labels claim it has, and there is a clear "this one" without touching the data:

```js
plotOptions: {
  pie: {
    hoverOutline: {
      show: true,      // default
      size: 8,         // band thickness, px
      gap: 0,          // extra clearance beyond the slice stroke
      opacity: 0.3,
      color: undefined // defaults to the slice colour
    }
  }
}
```

**Click** slides the slice out of the pie along its own mid-angle, rather than growing it. It is translated, never re-drawn, so the shape and the quantity it encodes are unchanged and a real gap opens between it and the rest of the pie. Its percentage label (and its outer name label, if you use those) travel with it, and the darken is gone, since moving is signal enough:

```js
plotOptions: { pie: { expandOnClick: true, expandOffset: 10 } }  // px, default 10
```

Both animate, and both respect `chart.animations.enabled`.

If you want the old behaviour, the filters come back when you turn a visual off: `hoverOutline.show: false` restores the hover lighten, and `expandOnClick: false` restores the click darken. `states.hover.filter.type: 'none'` still means no hover feedback at all. polarArea keeps the filters either way, since its radius *is* the value there and sliding a slice outward would read as a bigger number. A drilldown pie or donut does not slide either: a click there is navigation, so the slice would pull out only to be discarded by the drill it just triggered.

On the workaround in this thread, driving it from `dataPointMouseEnter` by hand: that still works, and it is still the way to go if you specifically want the slice to *move* on hover. What is different now is that hovering has a built-in affordance, so you should not need to reach for it just to get feedback.

Thanks for the patience on this one. Six years and no reply from us was too long, and the discussion here (plus the fact that people kept commenting after the bot closed it) is what got it picked up. Upgrade to v6.9.0 and above to use this.
