### ISSUE TITLE
Line graph with option curve: "stepline" displays wrong values

### ISSUE THREAD

**Issue by mattilind** [apexcharts/apexcharts.js#1872]
# Bug report

## Codepen

https://codepen.io/malind/pen/QWNMKJr

## Explanation

- What is the behavior you expect?

Value displayed in chart should change to "1" at "05:00".  It should be displayed as "1" until the next value is received ("0" at "06:00").

- What is happening instead?

Value displayed in chart changes prematurely to "1" at "04:00". The following value changes prematurely to "0" at "05:00". Notice also the difference between the chart value and the tooltip.

![image](https://user-images.githubusercontent.com/48258345/91824246-22db9000-ec43-11ea-8f07-084b3729aecc.png)

- What error message are you getting?

None.

**Comment by robotkala** [comment]
any updates on this?

**Comment by robotkala** [comment]
please

**Comment by cardobherUS** [comment]
Hi! maybe you have already solved it but it is not a bug. The problem comes from the order of the dates, you have to put them from the oldest to the newest. Here is your code corrected, hope it helps you. https://codepen.io/carlosDoblado/pen/oNopeRE

![imagen](https://user-images.githubusercontent.com/56033933/154511708-6ebe9c86-b7f4-4c87-9dcf-5241a6ce5ea6.png)

**Comment by brianlagunas** [comment]
Thanks @cardobherUS for helping out and providing the solution.
