### ISSUE TITLE
Monochrome Settings Override Behavior

### ISSUE THREAD

**Issue by astone2014** [apexcharts/apexcharts.js#1940]
**Is your feature request related to a problem? Please describe.**	
When a theme is selected like a palette it is the default, then it later gets overridden by other options such as colors.

When a monochrome color theme is enabled it cannot be overridden by options such as colors.

**Describe the solution you'd like**	
Monochrome theme should be overwritten with settings in the same way a palette theme is overwritten.

**Describe alternatives you've considered**	
On change of theme setting `monochrome: { enabled: false }` if the colors are set. (not necessary with palettes)

**Additional context**
Monochrome Behavior (no effect):
![image](https://user-images.githubusercontent.com/22425467/94436928-11ff3b00-016b-11eb-84a1-5c6f8a187a8c.png)
Palette Behavior:
![image](https://user-images.githubusercontent.com/22425467/94436962-1d526680-016b-11eb-90b5-0dda59d85fff.png)

**Comment by junedchhipa** [comment]
That's intentional.
The priority is this way
 
(highest to lowest)
colors -> palette
fill.colors -> colors
monochrome.color -> colors

So, palettes have the lowest priority because they are not defined by users. Fill colors and monochrome colors are set by the user specifically hence they a higher priority. Hope this clears up!

**Comment by astone2014** [comment]
Thanks for the information 👍
