### ISSUE TITLE
Responsive charts with aspect ratios

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#20]
We are on the way of replacing Chartist with Apex and some charts have an aspect ratio specified (instead of height) to make the chart truly responsive.
Here's a list of supported ARs https://codepen.io/jesperkc/pen/EyWevN and it would be nice to have these in Apex too.

**Comment by junedchhipa** [comment]
Interesting point!
I just checked out how chartist handles it, and it seems most of the settings are in CSS. The user can specify the class, and it will set the aspect-ratio/height accordingly.

I think, calculating in JS will allow me to get it done in less code, as so much CSS will increase the bundle size.
Very good suggestion though, I never realized why my charts were looking a bit odd in very small devices.

**Comment by alex-e-leon** [comment]
@junedchhipa This looks like an old issue, and I'm not sure whether your thinking on this has changed/progressed, but without looking deeply at the source code I think that if apex switched from using `<svg width="x" height="y">` with `<svg viewbox="0 0 x y">` it could go a long way to making the charts properly responsive.

I guess the big blocker for this might be if you're doing other position calculations in JS based on the overall width/height rather than the rendered width height of the actual svg elements.

Thoughts?

**Comment by alex-e-leon** [comment]
@junedchhipa This looks like an old issue, and I'm not sure whether your thinking on this has changed/progressed, but without looking deeply at the source code I think that if apex switched from using <svg width="x" height="y"> with <svg viewbox="0 0 x y"> it could go a long way to making the charts properly responsive.

I guess the big blocker for this might be if you're doing other position calculations in JS based on the overall width/height rather than the rendered width height of the actual svg elements.

Thoughts?
