### ISSUE TITLE
Heatmap Yaxis offset labels don't work

### ISSUE THREAD

**Issue by violacambie** [apexcharts/apexcharts.js#2033]
# Bug report
**HEATMAP**: yaxis --> labels --> **offsetY** doesn't work for Heatmap with large amount of rows.

## Codepen
https://codepen.io/Cambie/pen/wvWQoKR

## Explanation

- What is the behavior you expect?
I would want to see the labels aligned with their respective rows
- What is happening instead?
with a big amount of rows the labels start to lose the alignment
- What error message are you getting?
none

**Comment by JulMack** [comment]
It seems to me this doesn't work at all. I'm using it on Angular11 and the yaxis.labels.offsetY option does not do anything in my heatmap. I was able to work around this, tho, with the style.cssClass option and a global style with translateY(3px). I guess this was necessary because for Angular Material's Roboto font the labels were not correctly aligned by themself.

**Comment by EduardChernyak** [comment]
It is still reproduced.

**Comment by brianlagunas** [comment]
@EduardChernyak I will reopen his issue since you reported this is still and issue for you.

**Comment by cart-before-horse** [comment]
It seems like the offset is still present (reproduction link in op). Its growing bigger as the series getting larger.
I tried to fix it here pr #4429, now ticks and labels consistent no matter how many rows there are in total.

However i'm slightly concerned about labels positions
Not that they used to be perfectly aligned - more like their baseline was ~2px lower than corresponding tick (quite noticeable with larger font), and now it's more like the baseline matches the tick perfectly, rendering labels ~2px higher.

**Comment by cart-before-horse** [comment]
nevermind, looks like parsing style attribute did the trick
