### ISSUE TITLE
Null values in combination with gradient fill and smooth stroke results in restarting gradients and weird looking lines

### ISSUE THREAD

**Issue by EeeDotZee** [apexcharts/apexcharts.js#2094]
# Bug report

## Codepen

https://codepen.io/eliazzz/pen/GRjqRzx

## Explanation

If a data series contains a null value combined with using a gradient fill (either for background or the line itself) and a "smooth" stroke results in the gradient restarting at every point, which makes it looks weird as in the codepen example above. 

Note: This only happens with the smooth stroke setting, it doesn't happen with 'straight' or 'stepline'

**Comment by knox31085** [comment]
And if there are several identical values they wont be rendered at all...

See the following data:
```
{
          name: 'test',
          data: [null, 15, 12, 12, 12, 12, 12, 12, 16, 14, 12, null, 14, null, null, null]
}
```

The 12'er should result in a flat line, which isn't rendered at all.

**Comment by stuartwiener** [comment]
Found this workaround: 

Rather than using null values to extend the range of a chart, you should explicitly set `xaxis.min` and `xaxis.max` (documented [here](https://apexcharts.com/docs/options/xaxis/) ), and then the area gradient is rendered correctly, while the intended range of your chart is still covered.

This won't quite work if you have null values interspersed in your data, as that would result in multiple SVG shapes being rendered underneath the hood.
