### ISSUE TITLE
X axis - reversed graph

### ISSUE THREAD

**Issue by a-davityan** [apexcharts/apexcharts.js#2323]
**Is your feature request related to a problem? Please describe.**	
Not a problem but a configuration for x-axis similar to y-axis.

**Describe the solution you'd like**	
A config `reversed: Boolean` for x-axis.
Should work in a same way as it works for y-axis but just flips the graph by x-axis.

**Describe alternatives you've considered**	
No alternatives.

**Additional context**	
Nothing to add.

**Comment by richardNZ16** [comment]
I am also interested in this feature. I thought i could pre-reverse the data for the series, so instead of going 0-8000 in my array of [0] -> [100], i reversed my data so that [0] = 8000 and [100] = 0.

This did nothing to how the series was rendered however.. 
Is there a workaround to do what we need here? Surely the renderer should be plotting in order that the series data comes in?
