### ISSUE TITLE
Download PNG is not working with Intl.NumberFormat

### ISSUE THREAD

**Issue by petersanta** [apexcharts/apexcharts.js#2512]
# Bug report
When I turn on the toolbar for a chart and enable the download feature for exports, it can not create a PNG file.
SVG works fine (without any alert or bad character in the source of the SVG).

It looks the problem is connected to Intl.NumberFormat(). It works with some locales (en-GB) but with other ones (hu-HU) it doesn't.

## Codepen

[Codepen sample](https://codepen.io/petsan23/pen/YzVGxWb)

## Explanation

- I'd like to download the chart as a PNG
- Nothing happens, the PNG file is not created
- I don't get an error message

Thank you for your help!

**Comment by petersanta** [comment]
Hi, could you please help, is it solved already? Thank you!

**Comment by brianlagunas** [comment]
I looked into this and I found the cause of the issue. It seems that this is happening because the format `hu-HU` contains an invalid character when trying to build an SVG URI.  It uses a non-breaking space character represented by the `&nbsp;` when converted to an svg string. This character seems to break the svg string creation which breaks the png export.

To fix this, simply convert the non-breaking space character (`\xa0`) to a space character (`\x20`):

```
let ret = Intl.NumberFormat('hu-HU').format(val)
ret = ret.replace('\xa0', '\x20')
```
or you can simply use
```
let ret = Intl.NumberFormat('hu-HU').format(val)
ret = ret.replace('\xa0', ' ')
```
Either will work.
