### ISSUE TITLE
TimeLine labels keep showing when zoom

### ISSUE THREAD

**Issue by sbgaia** [apexcharts/apexcharts.js#2535]
When I zoom in on a timeline chart, the blurry data labels continue to show. I haven't found a way to hide them. With more data on the same row zoomed in, the labels overlap. Here is the code.

https://codepen.io/foglights/pen/gOWvQOo

![Immagine](https://user-images.githubusercontent.com/42733642/127243439-1422383d-07d1-45c7-a4fc-4d66ad0d38b6.png)

**Comment by SixFourSeven-2077** [comment]
Greetings, any news on this bug? Please consider the issue another user has encountered : https://stackoverflow.com/questions/72029982/how-can-i-fix-overlapping-of-data-labels-in-react-apex-charts

Same causes, same problem : enabling DataLabels on a Timeline Chart causes them to be displayed even if the user zoomed in, which is not the behavior expected since the DataLabels concerns data not displayed.

**Comment by randomnessdev** [comment]
Same issue here

<img width="712" alt="image" src="https://github.com/apexcharts/apexcharts.js/assets/35777896/6f885cf1-ca15-4507-a217-b6cec122315b">

tried many workaround without success, any idea ?

**Comment by junedchhipa** [comment]
@randomnessdev the data-labels overflowing on y-axis is a separate issue. Please open a new issue with line chart-type.
The reported issue is for timeline charts.
