### ISSUE TITLE
Tooltip is still present when series is collapsed while y-axis showAlways is true

### ISSUE THREAD

**Issue by alekbless** [apexcharts/apexcharts.js#2566]
# Bug report

### Description

Tooltip is still present when series is collapsed

### Steps to Reproduce

1. In any multi series chart set one y-axis to showAlways: true
2. Collapse one or all series 
3. Hover mouse at the hidden series

### Expected Behavior
The tooltip should be hidden with the series data?

### Actual Behavior
Tooltip is still present over the collapsed series.

### Screenshots

<img width="675" alt="tooltip-visible" src="https://user-images.githubusercontent.com/6172971/130851241-cdb83013-7dfe-47b2-91e9-412983778eff.png">

### Reproduction Link

Link: https://codepen.io/5less/pen/mdwyGzV
Working version in 3.19.0: https://codepen.io/5less/pen/XWgJPyy

**Comment by alekbless** [comment]
Updated with Codepen from an earlier release where the tooltip is hidden as expected.

**Comment by 4eveRS** [comment]
Any updates on this issue?

**Comment by justinyng** [comment]
Hi, I believe I am also experiencing this same issue or very similar and started to follow this post and am curious on updates as well. However to note, I am using the Angular wrapper version of the ApexCharts library on an Angular 12 project.

Similar to @alekbless, at one point this wasn't an issue as the sample demo code on the website shows it working in codepen with a older version on Angular and apexchart library: https://apexcharts.com/angular-chart-demos/mixed-charts/multiple-y-axis/ (in this version, it is working as expected if you modify the code to set the showAlways flag to true for one or any of yaxis).

However, I copied the multiple-y-axis demo code to a new project I created (in Angular 12, using newer versions of the library "apexcharts": "^3.32.0" and "ng-apexcharts": "^1.6.0") and set the showAlways flag to true, but it looks very similar to the same bug described above:

![image](https://user-images.githubusercontent.com/26607665/146994097-580449e3-e90a-4c5e-895e-7f4cedcadf4b.png)
Here, the Income series shows up in the tooltip when the series has been disabled through clicking the legend.

Let me know if I can help provide additional information, otherwise, I will continue to follow this issue for any updates, thanks.
