### ISSUE TITLE
borderRadius is not working properly with type "Bar with Negative Values"

### ISSUE THREAD

**Issue by plapointe6** [apexcharts/apexcharts.js#2592]
### Description

If you follow [this exemple](https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-negative-values/) and you try to add a border raduis, it won't work properly. The border radius is only applied to the left bars and not to the right bars.

My code : 
```js
  var options = {
    series: [
      {
        name: 'Males',
        data: [0.4, 0.65, 0.76, 0.88, 1.5, 2.1, 2.9, 3.8, 3.9, 4.2, 4, 4.3, 4.1, 4.2, 4.5,
          3.9, 3.5, 3
        ]
      },
      {
        name: 'Females',
        data: [-0.8, -1.05, -1.06, -1.18, -1.4, -2.2, -2.85, -3.7, -3.96, -4.22, -4.3, -4.4,
          -4.1, -4, -4.1, -3.4, -3.1, -2.8
        ]
      }
    ],
    chart: {
      type: 'bar',
      height: 440,
      stacked: true
    },
    colors: ['#008FFB', '#FF4560'],
    plotOptions: {
      bar: {
        horizontal: true,
        barHeight: '80%',
        borderRadius: 5   // Here is the issue ...
      },
    },
    dataLabels: {
      enabled: false
    },
    stroke: {
      width: 1,
      colors: ["#fff"]
    },
    grid: {
      xaxis: {
        lines: {
          show: false
        }
      }
    },
    yaxis: {
      min: -5,
      max: 5,
    },
    xaxis: {
      categories: ['85+', '80-84', '75-79', '70-74', '65-69', '60-64', '55-59', '50-54',
        '45-49', '40-44', '35-39', '30-34', '25-29', '20-24', '15-19', '10-14', '5-9',
        '0-4'
      ],
      title: {
        text: 'Percent'
      },
      labels: {
        formatter: function (val) {
          return Math.abs(Math.round(val)) + "%"
        }
      }
    },
  };

  var chart = new ApexCharts(document.querySelector("#chart"), options);
  chart.render();
```

### Steps to Reproduce

1. Try the code below

### Expected Behavior

All bars have rounded corners.

### Actual Behavior

Only one side of the chart has bars with rounded corners.

### Reproduction Link

https://codepen.io/plapointe6/pen/QWgEKwJ

**Comment by brianlagunas** [comment]
I found the offending code. Now I just need to find a fix that doesn't break anything else :)

**Comment by brianlagunas** [comment]
By the way, this only happens when the bar chart is stacked. If you set `stack: false` this it will work. However, it will not look the same.

**Comment by brianlagunas** [comment]
The reason this is happening is because when using a stacked bar chart, there is logic that prevents any series from having a radius applied except the very last one. This results in a more appealing visual appearance and ensures all the stacked series data can be properly read. Example:

![image](https://user-images.githubusercontent.com/835562/132954709-58b75692-8d85-4cf7-918e-98a726429706.png)

In this specific case, you are using a stacked bar chart, however, the series are not contiguous, instead they are opposite. This results in only the last series in the index to have the radius applied (the Females). 

To fix this, I need to add another property to the bar plot options that will force the radius on all the series of the stacked bar chart.  As you know, naming things can be hard, and this is a very specific scenario, so I don't imagine this option being used very often.

Here are a couple of ideas I had for the property name:
- borderRadiusOnAllStackedSeries
- borderRadiusOnStackedSeries
- forceBorderRadiusOnAllStackedSeries
- forceBorderRadiusOnStackedSeries
- forceBorderRadius

The usage will look somethiing like this:
```
plotOptions: {
  bar: {
    horizontal: true,
    barHeight: '80%',
    borderRadius: 5,
    borderRadiusOnAllStackedSeries: true
  },
      }
```

Let me know what you think and if you have any ideas on good property names to apply the border radius on all stacked series

**Comment by junedchhipa** [comment]
You're right, that was the intended behavior.
I like `borderRadiusOnAllStackedSeries` property which is clear from the name that the user wants border-radius on all series of a stacked chart.
Feel free to create a PR with this change.
(Please also add a property to the typescript file)

**Comment by brianlagunas** [comment]
Another option would be to avoid adding a property.

We could add a check that if there are exactly two series and the first series has negative values then add the radius, otherwise we don't.

This is an edge case and I would prefer not to add a property to the API if we could help it.

Thoughts?

**Comment by plapointe6** [comment]
Just an idea: the logic could be the same as for property `colors`. Allow specifying an array for the property `borderRadius`. So, It could be possible to set a specific border-radius for each series. Specifying only one value will keep the current behavior (no breaking changes). In my case, after the changes, I could set `borderRadius: [5, 5]`.

**Comment by brianlagunas** [comment]
@plapointe6 that's a really good idea.  Let me play around a but and see how that works out.

**Comment by brianlagunas** [comment]
@plapointe6 Your idea worked perfectly and actually ended up being a new feature. You can now assign a border radius to a specific series in your chart. See PR #2614
