### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by rajeevverma076** [apexcharts/apexcharts.js#2634]
No overload matches this call.
  Overload 1 of 2, '(props: Props | Readonly<Props>): ReactApexChart', gave the following error.
    Type '{ stroke: { curve: string; }; markers: { size: number; }; xaxis: { categories: never[]; }; chart: { width: string; }; }' is not assignable to type 'ApexOptions'.
      The types of 'stroke.curve' are incompatible between these types.
        Type 'string' is not assignable to type '"smooth" | "straight" | "stepline" | ("smooth" | "straight" | "stepline")[] | undefined'.
  Overload 2 of 2, '(props: Props, context: any): ReactApexChart', gave the following error.
    Type '{ stroke: { curve: string; }; markers: { size: number; }; xaxis: { categories: never[]; }; chart: { width: string; }; }' is not assignable to type 'ApexOptions'.

**Comment by brianlagunas** [comment]
You did not provide an app to reproduce the issue

**Comment by sarahmattar** [comment]
This is still a legitimate issue in the typecasting of the original ApexCharts library. I am seeing it with the `align` property on the `ApexTitle` type and the `ApexNoData` type as well inside a production app. Both of these types are referenced in the `ApexOptions` type for the title and noData keys respectively, this is the overload error I am getting when passing the Options object: 

```
const title = {
    text: props.chartTitle,
    align: "left",
    margin: 50,
    style: {
      fontSize: "1.25rem",
      fontFamily: "Open Sans",
      fontWeight: 100,
      color: COLORS.gray["900"],
    },
  };

  const noData = {
    text: "No data to display",
    align: "center",
    style: {
      color: COLORS.blue,
      fontSize: "2rem",
      fontFamily: "Open Sans",
    },
  };

  const options = {
    title,
    noData,
  };
```

In VSCode, and on my local client, I get this error: 

```
No overload matches this call.
  Overload 1 of 2, '(props: Props | Readonly<Props>): ReactApexChart', gave the following error.
    Type '{ labels: string[]; colors: string[]; title: { text: any; align: string; margin: number; style: { fontSize: string; fontFamily: string; fontWeight: number; color: any; }; }; noData: { text: string; align: string; style: { ...; }; }; }' is not assignable to type 'ApexOptions'.
      The types of 'noData.align' are incompatible between these types.
        Type 'string' is not assignable to type '"left" | "right" | "center" | undefined'.
  Overload 2 of 2, '(props: Props, context: any): ReactApexChart', gave the following error.
    Type '{ labels: string[]; colors: string[]; title: { text: any; align: string; margin: number; style: { fontSize: string; fontFamily: string; fontWeight: number; color: any; }; }; noData: { text: string; align: string; style: { ...; }; }; }' is not assignable to type 'ApexOptions'.

```

I can create a dummy app to demo the issue but given that it is a type signature/overload issue, it will not be able to be seen in anything else other than a IDE error message if you clone the code, or an error page on `localhost:3000`. It's a shame this issue was closed/dismissed a year ago because the original poster did not have a live hosted app to show what the copied and pasted messaged already successfully conveyed.
