### ISSUE TITLE
(Windows) Error when execute npm install apexcharts --save

### ISSUE THREAD

**Issue by jrozos** [apexcharts/apexcharts.js#278]
## [Explanation](url)

- What is the behavior you expect?
Installed properly
- What is happening instead?
Attached images with the errors, when trying to execute de "npm install apexcharts --save"
- What error message are you getting?
Attached images

![1](https://user-images.githubusercontent.com/16327107/51347676-5f567a00-1a66-11e9-9236-6a5d4efd967a.JPG)
![2](https://user-images.githubusercontent.com/16327107/51347677-5f567a00-1a66-11e9-8fb5-251c10e1554b.JPG)
![3](https://user-images.githubusercontent.com/16327107/51347678-5f567a00-1a66-11e9-80f6-d8a7d68d7cc6.JPG)
![4](https://user-images.githubusercontent.com/16327107/51347699-6da49600-1a66-11e9-85c2-8b700ac218bc.JPG)

**Comment by GerardMetal** [comment]
I have the same error.
## Environment
- SO: Windows 10 Home
- Node -v: 11.2.0
- npm -v: 6.4.1
- Laravel 5.6

I don't understand the problem. Do will i have that downgrade the node-sass version?

**Comment by junedchhipa** [comment]
Can you try this?
npm rebuild node-sass
npm --add-python-to-path='true' --debug install --global windows-build-tools
npm install --global node-gyp
npm install

**Comment by cstlaurent** [comment]
Hi @jrozos , 

Unless I'm mistaken, the apexchart package do not depend on node-sass, this error must be caused by something else in your app, `npm` will try to build missing native modules with whatever `npm install` command you do.

Can you run `npm ls node-sass` to see which package is depending on node-sass?

Also, like @junedchhipa explained. You can fix this issue by installing the native build tools for windows by running `npm install -g windows-build-tools`. The procedure is explained here: https://www.npmjs.com/package/windows-build-tools

**Comment by GerardMetal** [comment]
The same error, after the whole process (without problems), i run command "npm run watch" 
Result:
![captura de pantalla 18](https://user-images.githubusercontent.com/23560749/51478988-a8524b00-1d52-11e9-9ad7-02f5b01acd24.png)

Yes, the versions are
Node -v: 11.2.0
npm -v: 6.4.1

**Comment by cstlaurent** [comment]
@GerardMetal I just tested with a fresh new Vue.js project created with the CLI and added apexcharts to it. It build and run without any issue on the latest node 10.x and 11.x on Windows and MacOS.

This is not related to apexcharts, you should check other part of your project that depends on sass. Apexcharts do not depend on any packages mentioned on this thread. 

@junedchhipa I think this issue can be closed, since it is not related to apexcharts.
