### ISSUE TITLE
Logarithmic Scale incorrectly displayed when some values are 1

### ISSUE THREAD

**Issue by JamieMair** [apexcharts/apexcharts.js#2909]
### Description

Height of bars are incorrectly set on a histogram with a logarithmically scaled y axis, this is shown in the first screenshot.

### Steps to Reproduce

1. Create a chart of histogram type series values of integers spanning from 1 to 100,000+, as in the first screenshot.
2. Set the yaxis to logarithmic:
```javascript
yaxis: {
  logarithmic: true
}
```
### Expected Behavior
The graph should roughly look like screenshot 2, expect the scale should be large enough to include all the values in the histogram (except zeros) - including the values of 1.

The screenshot is produced by applying a "fix" in the settings, making the yaxis on the chart options:
```javascript
yaxis: {
  logarithmic: true,
  min: 0.1
}
```
Notice that the chart cuts off all values which are 1, instead of setting the y scale to include "0.1".

### Actual Behavior

Larger values are clipped and not displayed according to the axis correctly.

### Screenshots

Screenshot 1:
![image](https://user-images.githubusercontent.com/13971435/150522452-e0046601-0bc2-4104-8581-e738e3c81bec.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/13971435/150522567-a9a23fb9-efac-4750-a3ea-eea5fdb58fca.png)

### Reproduction Link
Original:
https://codepen.io/jfm1029/pen/XWeLBKo
Almost fixed:
https://codepen.io/jfm1029/pen/mdBZjEE

**Comment by Ben0909** [comment]
I have similar problem . The problem with the wrong height of the bars when using logarithmic scale isn't only when inserting series value with the value 1.

For Example, the graph received for for series values of  [30, 430, 448, 470, 540, 580, 690, 1100, 1200, 1380]:

Actual Behavior:
![image](https://user-images.githubusercontent.com/43224373/156128113-4892c1a6-27bd-4d28-82b7-e7920daa89af.png)

Expected Behavior:
![image](https://user-images.githubusercontent.com/43224373/156128466-9f2b7b40-6df2-4aab-94a7-28aff86ac8b7.png)
