### ISSUE TITLE
Control which area is selected for tooltip 

### ISSUE THREAD

**Issue by grmorozov** [apexcharts/apexcharts.js#293]
**Codeopen**
https://rj4yj8wxrm.codesandbox.io/

**Explanation**
On a stacked area chart you may point cursor on top area, while tooltip still show an area below. It seems, that the closest point to the cursor is selected. Would be nice to be able to override this behavior. Let's say I want tooltip to always show data for a point from the serie cursor is on.

**Comment by junedchhipa** [comment]
In a non-shared tooltip, the tooltip shows for the closest point of the closest series. This is the expected behavior and I don't see any issue in the codepen. Maybe I misunderstood what you're trying to convey.

I suggest you also give `followCursor: true` property a try to make tooltip follow wherever the cursor goes. - https://apexcharts.com/docs/options/tooltip/

**Comment by grmorozov** [comment]
> In a non-shared tooltip, the tooltip shows for the closest point of the closest series.
I would like to be able to override this behavior.

**Comment by junedchhipa** [comment]
Sorry, this is not possible currently.
I would like to see a working example what you're trying to achieve (an example from another chart library is fine).
