### ISSUE TITLE
Feature Request: Angular bindings

### ISSUE THREAD

**Issue by jimfilippou** [apexcharts/apexcharts.js#33]
The company I work for, would like to contribute to this issue by making an Angular 4+ wrapper for Apex charts. We specialize in Angular 4+ having a large portfolio of Angular projects. Let me know if you're interested. 😃

**Comment by junedchhipa** [comment]
Hi @jimfilippou 
I have recently released vue.js bindings and react.js component for ApexCharts is coming very soon.
But, as of now, I have no experience working with Angular. I have some plans for it, can't give a date when it will happen.

If anyone wants to contribute, let me know ;)

**Comment by jimfilippou** [comment]
@junedchhipa i have updated my comment, take a second look

**Comment by junedchhipa** [comment]
@jimfilippou That sounds great!
Warning! Currently, there are no unit tests - as I have some major issues getting unit tests to work with SVG.js correctly. I am planning to do some integration/e2e tests to ease adding new features, but you/your team might face some difficulties due to a lack of these crucial things.

If you still want to go ahead, please get in touch with me on my email - so I can help with any initial hurdles you might encounter ;)
