### ISSUE TITLE
Empty csv file when first series is not visibile on chart.

### ISSUE THREAD

**Issue by w4ller** [apexcharts/apexcharts.js#3359]
### Description

Deselecting first series name and trying downloading csv file will produce a csv file with only columns names.

### Steps to Reproduce

1. Deselect first series from legend on a chart with multiple series displayed
2. Navigate to "download CSV" and click it
3. Open csv file downloaded.

### Expected Behavior
Downloading csv file should include all data of visibile series on chart.

### Actual Behavior
When first series is not visibile on chart cause we deselected it from legend, downloading csv file will have only columns name and no data will be present.

### Reproduction Link
https://codepen.io/apexcharts/pen/bxzgZJ

**Comment by brianlagunas** [comment]
This is by design. If you hide the data from the chart, it is not included in the export. As an end-user, if I hide data from a chart and export, I would not expect the hidden data to be in the export, because I only wanted to export the data I see in the chart.  If you like you can submit a feature request to provide an option to export all data on export.
