### ISSUE TITLE
Always display Y-Axis even when the series is deselected

### ISSUE THREAD

**Issue by D0ct0rBish0p** [apexcharts/apexcharts.js#339]
Hi there, please consider this Codepen example: https://codepen.io/D0ct0rBish0p/pen/XOwdxW

I have assigned the Y Axis for Series 1 and Series 2 both to Series 1, and I always want to display only a single Y Axis for either series. So I've set the second Y Axis to "show: false" which produces the required result.

However, as soon as I disable Series 1 by clicking on it in the Legend, it hides the left Y Axis and no Axis is displayed anymore on the left side. Is it possible to have an option, for example "alwayShow: true" or something to this effect ?

I hope my example is clear, please let me know if I need to provide additional details.

**Comment by junedchhipa** [comment]
Good point, it looks weird to have a series visible with no y-axis because it is associated with a hidden y-axis.

1. I will check if the series which is visible has an associated y-axis. If it is, I will avoid hiding it.
2. I will provide a property "alwaysShow" as suggested by you.

I will try the 1st one before providing the new option.

**Comment by D0ct0rBish0p** [comment]
Thank you for the quick response ! I'm really loving Apexcharts so far and am working on implementing it into my reporting dashboards as replacement for morris charts. Really awesome work.

Looking forward to have this feature implemented.

**Comment by junedchhipa** [comment]
I have provided a new property `yaxis.showAlways: true` as the 1st option I mentioned above didn't really work well. Will release a minor version soon.
