### ISSUE TITLE
Toggled (deselected) series in tooltip after updateSeries()

### ISSUE THREAD

**Issue by paaaz** [apexcharts/apexcharts.js#372]
## Codepen

[https://codepen.io/anon/pen/gEMBvL](https://codepen.io/anon/pen/gEMBvL)

## Explanation

- What is the behavior you expect?
A deselected Series (toggled) should not be in the tooltip after an updateSeries() call
- What is happening instead?
The deselected Series is displayed in the tooltip after calling updateSeries()
See Codepen example after clicking the button

**Comment by LuKaa** [comment]
This issue is still not fixed for me with using react-apexcharts.
Iam using 3.8.2 so i guess this should be fixed right ?

This this a problem with the react wrapper or could somelse verify that this issue still exists?

Iam updating teh series data like this:

`ApexCharts.exec('chart', 'updateSeries', [
                {data: this.state.OrderData.revenue},
                {data: this.state.OrderData.shipping},
                {data: this.state.OrderData.adspend},
            ]);`

And iam toggling the series like this:

` ApexCharts.exec('chart', 'toggleSeries',"Revenue");`

I want to point out that the toggling is working fine and there is not issue with updating the series just the toggle-state seems to get lost.
