### ISSUE TITLE
Zoom Area Chart : Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Heidet** [apexcharts/apexcharts.js#3748]
Problem with Apex chart, on a chart area.

When zooming by selection with the mouse on the chart, an error appears:
"Cannot read properties of undefined (reading '0')"

Yet with the unmodified example from the .

apexcharts@3.37.2
react-apexcharts@1.4.0
react@18.2.0
react-router-dom@6.10.0

**Comment by AngelFernandezSobrino** [comment]
I have the same issue, it is related to the moveDynamicPointOnHover [function](https://github.com/apexcharts/apexcharts.js/blob/c46cf9024306f3188ab56d886d3ce40bd580f980/src/modules/tooltip/Position.js#L240). I have not gone deeper at seeing this issue.

The exception raises at line 259, somehow, pointsArr[capturedSeries][j] it's undefined. It happens a lot more on the right side of the chart, when data is outside the chart view. As an example, I have a chart with event points (time-based, with points of each series at different times), with three series. When the cursor is placed at a position where one of the series next point (at the right of the cursor in the x-axis) is outside the time range of the chart, the error is raised. The tooltip does not move either, is like freeze (because the moving function has the exception so does not work). I have seen that this happened at other moments, but I don't see any other pattern, and it's rarer.

I have not analyzed deeply how the tooltip works, but looking at the behavior, it seems that the tooltip wants to move to a point at the right of the cursor which is outside the chart. Like, if the detector of the point next to the cursor does not consider the zoom of the chart, just the whole data, and when it tries to move the cursor to that point it is not on the chart.

I have tried to use the src to debug properly, but I'm using nextjs react-apexcharts and don't figure out how to switch properly between dist and src.

**Comment by brianlagunas** [comment]
Did not follow bug template instructions

**Comment by Heidet** [comment]
I just tested on their site, and look at the developer tools (browser console), they have the same problem.
The same error return in the console.

Except that they are not blocking because they are not in "dev" mode but in "prod" mode so the errors do not go up on the interface.

So it is indeed 100% sure that the problem comes from them.


<img width="563" alt="image" src="https://user-images.githubusercontent.com/34238777/229131770-c46cf320-4fd7-4e34-b0d1-eb9ed1734e21.png">

**Comment by AngelFernandezSobrino** [comment]
Yes, it is a bug in the library, but you should use the Bug template on a new issue.

**Comment by yaswanthpilla17** [comment]
Th same error is getting while integrating the charts with data and when i'm loading the outside range of the date and it is showing the same error. Please try to resolve it.
