### ISSUE TITLE
xaxis labels showing weird(incorrect) values

### ISSUE THREAD

**Issue by BlvckParrot** [apexcharts/apexcharts.js#4067]
### Description
The x-axis labels are displayed in mismatched values as decimal numbers, even though the data for the chart is integers.

### Steps to Reproduce

1. install latest version of apexcharts
2. create basic bar chart
3. provide data as this:
<img width="171" alt="Snímek obrazovky 2023-10-19 v 13 52 28" src="https://github.com/apexcharts/apexcharts.js/assets/102683622/2d2f1c85-8dec-49bd-bfdf-ae5ce67705e0">

notice that x coordinate values are integers.

### Expected Behavior
The labels on the x-axis should correspond to the data provided as the tooltip label does.

### Actual Behavior
The labels on the x-axis do not correspond to the data provided.

<img width="1398" alt="Snímek obrazovky 2023-10-19 v 13 53 21" src="https://github.com/apexcharts/apexcharts.js/assets/102683622/9727fb60-41e2-4eea-a65f-b4ffecde6fad">

Also, the values change when you console.log them or not:

<img width="682" alt="Snímek obrazovky 2023-10-19 v 14 01 10" src="https://github.com/apexcharts/apexcharts.js/assets/102683622/e559cd45-1c5d-4a8f-80ed-e6f10c27a8e7">

<img width="1205" alt="Snímek obrazovky 2023-10-19 v 14 03 30" src="https://github.com/apexcharts/apexcharts.js/assets/102683622/81e88eb2-ec4c-45f6-a2a5-513669f5ac2c">

### Reproduction Link
I recreated the code several times
template Codepen [here](https://codepen.io/wsxder/pen/NWeQZLy)
StackBlitz TypeScript [here](https://stackblitz.com/edit/vitejs-vite-gjt6r4?file=src%2Fmain.ts)
StackBlitz React [here](https://stackblitz.com/edit/vitejs-vite-f8lboc?file=src%2FApp.jsx)

### When the problem occured
I found out that the problem occured in versions from @3.6.12 and above, the previous versions(@3.6.11 and lower) are working as expected.

![Snímek obrazovky 2023-10-19 v 14 18 11](https://github.com/apexcharts/apexcharts.js/assets/102683622/f73bb411-ab3a-4207-9b37-586a8576c020)

**Comment by 89erik** [comment]
I'm having a similar issue probably caused by the same bug. In a rangeBar chart where the ranges in the y-axis are floats, e.g. [1.1, 1.2], the tooltip always shows them as integers e.g. "1 - 1". If i define toolip.y.formatter, receiving two arguments (value, obj), then I see that it is called 7 times. The first two times (one per item in the range) it is called with integers as value and the object is undefined. The return value from these are assumedly the ones that are shown in the GUI. Then it is called once with the float value of the second part of the range, but still no object. Then finally two times for both parts of the range, with both the float value and the object containing series, seriesIndex etc). These latter four calls (allthough only two should suffice) have the correct arguments and should be the ones used to actually display the values, but they are not.

How to reproduce:
```
const options = {
    series: [
        {name: "A", data: [{x: "foo", y: [1.1, 2.1]}, {x: "bar", y: [3.1, 4.1]}]},
        {name: "B", data: [{x: "foo", y: [5.1, 6.1]}, {x: "bar", y: [7.1, 8.1]}]},
    ],
    chart: {
        type: 'rangeBar'
    },
    tooltip: {
        y: {
            formatter: (value, obj) => {
                console.log(value, obj)
                if (obj === undefined) {
                    return "this is always the displayed integer value " + value
                } else {
                    return "The value is now correctly float, and the obj contains rows and row index, but this is never displayed"
                }
            }
        }
    }
}
```

The log output when hovering the [7.1, 8.1] range:
```
7 undefined
8 undefined
8.1 undefined
7.1 {series: Array(2), seriesIndex: 1, dataPointIndex: 1, w: {…}}
8.1 {series: Array(2), seriesIndex: 1, dataPointIndex: 1, w: {…}}
7.1 {series: Array(2), seriesIndex: 1, dataPointIndex: 1, w: {…}}
8.1 {series: Array(2), seriesIndex: 1, dataPointIndex: 1, w: {…}}
```

**Comment by acocheo** [comment]
Same bug here

**Comment by BlvckParrot** [comment]
If you're looking for a quick fix, just convert the labels to string.
