### ISSUE TITLE
RadialBar Gradient Fill not showing on IPhone Safari

### ISSUE THREAD

**Issue by bunnyboy911** [apexcharts/apexcharts.js#419]
## Codepen

[CodePen Link](https://codepen.io/anon/pen/XGxVxP?editors=1111) 

## Explanation

- What is the behavior you expect?
       - Show Radial bar on IPhone browser

- What is happening instead?
       - Radial bar portion of chart is not showing
       - When I change the type of the fill to "Solid," it shows up

- What error message are you getting?
       - None

**Comment by jicihome** [comment]
Hi!
Not sure if I have the same issue, but facing similar behavior.
I think it's related to how the script work for calculating the min-height of the parent.
In the example from @bunnyboy911 , you can see that height of chart is set to 270... but the min height is set to 188 (and this is use after for the div of the chart and svg). 
Min is set to 250 and reduced to 216. 
I think that because of this, the text in center is not perflectly centered like it should (and it is here: https://codepen.io/junedchhipa/pen/XyjEEL ... in the example of bunnyboy, you can see that flawless is lower than it should, not the case in your demo). I guess the text/datalabel is centered with the height correctly. I think also that in the demo, the min-height of chart 1 (and children) are set to higher than the height of options!
