### ISSUE TITLE
axes overlapping issue since 3.46.0 update

### ISSUE THREAD

**Issue by HannibalZA** [apexcharts/apexcharts.js#4254]
### Description
Axes labels are not auto-distributed to prevent overlapping (UI) on render anymore.
Since last update adding any kind of formatter to the Axis label breaks its ability to handle this.

### Steps to Reproduce

1. Create a simple bar chart
2. Plot as 100 max (percentages), and add a range of categories against which to plot various values (0-100)
3. Render chart, but restrict it's width to e.g. 250px.
4. Add a formatter to the x-axis labels to display/return as value + "%" so it is accurately illustrated.
5. Version 3.46.0 renders with all 10 data points rendered and overlapping
6. Change version to 3.45.2 and data points are rendered as 0, 20, 40, 60, 80 and 100, preventing overlapping

### Expected Behavior
![image](https://github.com/apexcharts/apexcharts.js/assets/2007626/5f18eb69-961e-4b8e-85d1-fa2699e3ff9b)

### Actual Behavior
![image](https://github.com/apexcharts/apexcharts.js/assets/2007626/dcd84c60-f613-4075-b667-78ba6d9ac3ad)

### Screenshots
See screens above...

### Reproduction Link
https://codepen.io/hannibalza/pen/YzggRaV
Modify the above codepen to use v3.45.2 from CDN, and switch back to 3.46.0 to show the issue.

**Comment by rosco54** [comment]
Let me take a look at it, as it's most likely due to changes that I've contributed.

**Comment by rosco54** [comment]
Problem (2) has been fixed in the pull request.

Regarding problem (1): hideOverlappingLabels does not appear to be implemented for horizontal charts as in your case.
However, the changes that I contributed in revision 3.46.0 do include an automatic tick-pruning feature that, if not activated automatically (due to user options taking priority), can be prioritised by adding "forceNiceScale: true". This process happens before final label formatting, so it doesn't take account of, eg, user concatenated text, so it's not therefore a proper substitute for hideOverlappingLabels, if or when that is fully implemented.
