### ISSUE TITLE
Force yaxis to alway draw '0' even with negative data

### ISSUE THREAD

**Issue by AndriiLutsiv** [apexcharts/apexcharts.js#4317]
### Description

I have faced an issue while working on my project. So there are charts that do not show '0' on yaxis. 
I tried forceNiceScalse: true, also tried playing with min-max and they didn`t help.
The only thing that worked for me is tickAmount, yet in my situation I see no way to calculate it for 5000 dynamic charts, so that each chart would have its own tickAmount.

### Steps to Reproduce

1. open this codepen https://codepen.io/A_n_d_r_i_i/pen/ZEZWjBj
2. Try to make the chart show '0'

### Expected Behavior
Chart has to draw '0' on yaxis

### Actual Behavior
Chart does not draw '0' on yaxis

### Screenshots
![chart](https://github.com/apexcharts/apexcharts.js/assets/66524005/c3b1a856-b531-4624-a633-f17a5909abe8)

### Reproduction Link

codepen https://codepen.io/A_n_d_r_i_i/pen/ZEZWjBj

**Comment by rosco54** [comment]
@junedchhipa I'd be happy to update the documentation if you'd like. Just let me know how and in what form.

@AndriiLutsiv you have specified both min and max for the yaxis and they are no longer advisory since 3.46.0. The range is therefore fixed at 35 (= max - min). This number can only be divided by 5 and 7, since ApexCharts always uses equal divisions for the ticks.

Some choices:

1) adjust your yaxis options to guarantee a zero tick, eg, min: -5, max: 30 (you can assume that a nice value like 5 will be used for the increments, or min: -4, stepSize: 4, if you want a specific increment, etc, or

2) don't specify at all and let ApexCharts figure out what min and max to use, that will include zero (generally/always).

Here's the result leaving out both the yaxis min and max settings.

![92gim6zf](https://github.com/apexcharts/apexcharts.js/assets/159597299/035eabf8-af34-4726-9d1d-75764f7c8290)

**Comment by AndriiLutsiv** [comment]
Thanks a lot for a reply. I`m sorry I had to adapt the codepen to a real case scenario. Here is an updated codepen that is from my project https://codepen.io/A_n_d_r_i_i/pen/jORrqLW. As we see somehow the '0' is missing on the yaxis also there is only 1 metric instead of several ones. I`m usning the most recent version of apexcharts. I wonder if it is possible to show '0' without min and max values. For some reason forceNiceScale didn`t help

**Comment by rosco54** [comment]
This is not a solution but I can show you what's happening.

The chart height is set to 200 pixels and in order to avoid overlapping
labels on the y axis, the ticks have been reduced. At 200 there isn't much
scope wrt the number of ticks. To see the ticks it actually computed set
the height to 300 in the template section at the top of your codepen js.

There are 11 ticks (plus the X axis at the bottom). Unfortunately 11 is a
prime number so you either get all 11 ticks or just 1 and nothing in
between, because tick increments must always be equal in ApexCharts.

I need to think about how to make this better than it is but in the
meantime all I can suggest, assuming your height of 200 can't be altered:

1) try, for example in this case, stepSize: 1.5

2) fake a zero line using a yaxis annotation. Say:


annotations: {
  yaxis: {
    y: 0,
    label: {
      text: ''
    }
  }
}
