### ISSUE TITLE
Growing graphs

### ISSUE THREAD

**Issue by johannegger** [apexcharts/apexcharts.js#460]
Hi again,
i was actually trying to replicate a different bug when by chance I was able to get this one into a [stackblitz](https://stackblitz.com/edit/typescript-yebrvd?file=index.ts)

On chrome/edge/firefox when you load the page the graph will grow until reaching a final height. 

ps. I'm on windows

**Comment by johannegger** [comment]
ah and btw, sorry for supplying a stackblitz and not a codepen - wasn't able to reproduce it there!

**Comment by Diegolml** [comment]
Apparently it has something to do with the way the div is created.
If you add `appDiv.style.height = "450px";` in line 7 that will stop the chart from growing.

https://stackblitz.com/edit/typescript-xs3bos?file=index.ts

**Comment by junedchhipa** [comment]
If you provide a "%" value in `chart.height`, the chart expects the parent element to have some fixed height. Otherwise, it goes into an infinite update. The infinite update happens because the chart listens on parent resize event, and updates again. As the update causes parent height to increase, it again fires the parent resize event, and so on.

So, if you provide '%' value in `chart.height`, please make sure, you have a fixed height parent.

**Comment by johannegger** [comment]
understood, thank you.
I know that this is out of scope but could you give me a hint on how to achieve that (fixed height parent) when working with flex-layout (fxFlex)? example: 3 charts on a page each one occupying a third of the height.

**Comment by junedchhipa** [comment]
Maybe try something like `height: 33vh` to the parent?

**Comment by johannegger** [comment]
ok, yes that looks much better! thank you!
