### ISSUE TITLE
Formating function in shared tooltips returns  "options.seriesIndex = 0"

### ISSUE THREAD

**Issue by petrsuchomel25** [apexcharts/apexcharts.js#478]
```
tooltip: {
            shared: true,
             y: {
                formatter: function(value,options){
                  return options.seriesIndex;
              }
}
```
If tooltip is set to **"shared:true"** then "options.seriesIndex" is always 0,
but if tooltip is set to **"shared:false"** then "options.seriesIndex" is set accordingly 

so if tooltip is shared you cannot find that value property in "options.series" with "seriesIndex" and "dataPointIndex"  

see it in action
https://codepen.io/petr-suchomel/pen/dLGBya

**Comment by andreas83** [comment]
i can confirm this issue, but for me seriesIndex is always 0, no matter what shared is set

**Comment by junedchhipa** [comment]
@petrsuchomel25 I can see the problem, but seriesIndex is really not captured in shared tooltip because fetching the value just based on `dataPointIndex` works fine for tooltips. I will see how this can be changed.

@andreas83 Can you post a codepen? If the tooltip is not shared, then `seriesIndex` should be different based on mouse position in a multi-series chart.

**Comment by petrsuchomel25** [comment]
@junedchhipa Thanks, very much so... in case You are wondering - Usecase is displaying percent values in tooltip...
https://codepen.io/petr-suchomel/pen/axmQxG

**Comment by Boldonglen** [comment]
Hi I have the same issue and this CodePen shows what the issue is that I am facing.

I have two different sets of series. One is the main data that I want to show in the tooltip and the other is a normalized version of that data (and therefore the data in the arrays are different).

N.B. For simplicity ive just set the normalized arrays to have random data. 

So essentially what I want to do is have the lines in the graph use the data from the normlizedArray and the tooltip to use the corresponding data from the realData array. 

As you can see in the CodePen if you hover over the individual point it shows the value for that point for all 3 of the lines. If the seriesIndex returned the correct index I the code I have implemented would work fine. Switching off shared would work but I need to show all of the data within the tooltip.

I hope I have explained this well enough, if not let me know.

[CodePen Example](https://codepen.io/boldonglen/pen/PgbZoo)
