### ISSUE TITLE
Transition of donuts charts are awkward

### ISSUE THREAD

**Issue by nick-keller** [apexcharts/apexcharts.js#48]
When data is updated the donut chart has awkward animations. Even when just changing the color for instance:
![donut](https://user-images.githubusercontent.com/2682443/44525473-4cbb5d00-a6e1-11e8-9de5-5143e1b4e829.gif)

**Comment by junedchhipa** [comment]
Yes, it doesn't look very pretty.
I will try something else for animation of updated pie/donut charts

**Comment by JCQuintas** [comment]
My animations are even weirder. The shape gets close to an '8' somehow then back to normal. I just disabled animation for donut chart while waiting for a fix.

**Comment by junedchhipa** [comment]
Right! 
I am guessing the '8' might be because of angle getting bigger than 360 when animating.
Will look into it.

**Comment by junedchhipa** [comment]
@unknownentity123 Thanks for your input.

I decided not to make it complicated and spent some more time to achieve a natural looking animation.

Finally, after some hours of playing with "startAngle" and "toAngle", I was able to achieve a very smooth transition.
Here is the end result
![pie-animation](https://user-images.githubusercontent.com/17950663/44970705-996c2700-af70-11e8-9cab-945d093f9fd7.gif)

**Comment by junedchhipa** [comment]
Here is the [codepen](https://codepen.io/apexcharts/pen/LJyPoq) example to play with

**Comment by nick-keller** [comment]
Awesome work here, this is looking perfect.
On the codepen the graph blinks when I click a button, a bit strange.

**Comment by junedchhipa** [comment]
Yes, I can see a bit of flickering, couldn't find an easy fix for this yet.
I will keep an eye on it though.

**Comment by unknownentity123** [comment]
Awesome...fantastic solution! Love the animation and it looks a lot more natural that what I was suggesting so a win all the way around!

**Comment by unknownentity123** [comment]
This morning, I'm working on using the newest release and the animation is perfect...however now any edge between slices that occurs past the 180 degree mark of the pie/donut creates a drop shadow on the previous slice that wasn't present in the previous releases before the fix. The drop shadow may also be present on less that 180 edges but I can't seem to really see it on my examples and might just be due to the angle of the shadow. Before the edges just a flat look and only the whole pie had a 3-D look with the drop shadow.

See my example used on my other post here:
[https://codesandbox.io/s/l2porqmrk7](url)

**Comment by junedchhipa** [comment]
Hi @unknownentity123 

The drop shadow was always there, but I changed 1 default setting in `fill.opacity`

```javascript
fill: {
  opacity: 1 // previously, it was 0.9
}
```

This change has made the shadow darker. If you want to lighten the shadow, you can reduce the opacity of the shadow.
In your example, try 0.05 instead of 1

The reason I did the `fill.opacity` change is to not modify the default color settings given by the user as it may cause inconsistencies with their theme colors.

**Comment by unknownentity123** [comment]
Gotcha...thanks! It's crazy that 0.2 made that much of a difference in visibility. Although I did remove the stroke between the slices which would break up and hide some of the shadow.

**Comment by junedchhipa** [comment]
This commit https://github.com/apexcharts/apexcharts.js/commit/1ded7a0fd46d039eb7d1fff1dffda6a3ec91150f fixes the flickering
