### ISSUE TITLE
Feature Request : Radar Chart 

### ISSUE THREAD

**Issue by LoiKos** [apexcharts/apexcharts.js#5]
Hi, first thanks for Apexcharts it looks awesome !

I would like to know if you plan to add new chart to the lib and more i'm especially looking for a radar chart ?

**Comment by junedchhipa** [comment]
Hi LoiKos,
I am open to adding more features/functionalities that can enhance the library as a whole. And, adding an additional chart-type is not at the top of the list for the moment.
I am willing to invest time to add more chart-types, but not 100% sure of the timeline when it will happen. The library is very new and at an early-stage. I am sure, a lot of things will change in the future depending on the feedback I get.
Thanks!

**Comment by jchamb** [comment]
@junedchhipa Curious if you've given any more thought on potential timeline for adding additional types. I too would love to see a Radar chart added. I have a project coming up where i'll most likely need them so may take a stab at seeing if i can get it implemented.

**Comment by junedchhipa** [comment]
Hi @jchamb, sorry for responding late.
Yes, since I closed this particular ticket - some additional chart-types were added (candlestick/step-line).
The next one in the timeline is the "Range Area Chart / Range Bar Chart".

I see that radar chart is also one of the most used charts after the basic ones, so definitely it's not going to be neglected. Cannot guarantee an ETA as there are areas which need more attention, but you can expect it in the next year's first quarter :)

**Comment by junedchhipa** [comment]
Released 2.6.0
Radar Chart examples - https://apexcharts.com/javascript-chart-demos/radar-charts/
Docs for additional options - https://apexcharts.com/docs/options/plotoptions/radar/
