### ISSUE TITLE
Feature Request: Min and Max radius for bubbles in bubble chart because they get too small and too big

### ISSUE THREAD

**Issue by Nivek92** [apexcharts/apexcharts.js#604]
**Is your feature request related to a problem? Please describe.**
I face the problem that some bubbles in my bubble chart get so small one can't even see them, when the difference between z values get's too big (or bubbles get too big when the difference gets too small).

**Describe the solution you'd like**
It would be awesome if one could set a min and max radius.

**Comment by josephpung** [comment]
<img width="1654" alt="Screen Shot 2019-07-02 at 11 43 04 AM" src="https://user-images.githubusercontent.com/30632611/60481098-96d87c00-9cbe-11e9-8449-52a681e51b34.png">

Im getting issues with the bubble chart as well, this is what they look like even though the z values are only 50-60 in difference

**Comment by junedchhipa** [comment]
Added new properties
`plotOptions.bubble.minBubbleRadius` & `plotOptions.bubble.maxBubbleRadius` which will allow to control the bubble sizes.

**Comment by BiggerNoise** [comment]
Awesome! Thanks for adding that, it's going to make my life much easier. I'll let you know if I have any issues when we get the update incorporated.

**Comment by BiggerNoise** [comment]
Went in without a hitch. Thanks for the update!

**Comment by BiggerNoise** [comment]
There's still a couple of issues with how bubble radii are calculated:

- The zRatio is calculated based upon the range of zValues. I don't think this will give the expected results when you have a set of large values that have a small range (e.g., 1000 - 1010).
- Using the zRatio gives a linear scaling of radius with the zValue. This looks weird. If my values range from 1-5, I would expect the bubble for 5 to be about five times the size of the bubble for 1, but because area is r^2, the bubble is 25 times the size. Perhaps quadratic scaling should be an option.
- I think that if a user has specified min & max bubble sizes, the output should scale between those sizes rather than doing a hard limit.

I'd be happy to do a P/R for these if they seem like changes that you would be open to accepting.

**Comment by junedchhipa** [comment]
@BiggerNoise Sure, I am happy to accept a PR.
