### ISSUE TITLE
updateOptions() reactivates toggled series in legend

### ISSUE THREAD

**Issue by paaaz** [apexcharts/apexcharts.js#656]
## Codepen

[Codepen](https://codepen.io/anon/pen/zQXMZd) 

## Explanation

- What is the behavior you expect?
The functions updateOptions should only change the options, not the state of the series if it is toggled or not

- What is happening instead?
updateOptions() reactivates a already deselected (toggled) series, but only in the legend not in the chart itself.
After that, clicking on the reactivated series has no effect at all!

**Comment by harshanaravindakshan** [comment]
I'm having the same issue as well. It would be nice (as stated above) for the updateOptions not to interfere with whether the series is visible or not.

**Comment by junedchhipa** [comment]
`updateOptions` will not interfere with the series unless the new options also contains `series` array.
If it contains `series` prop, a new method `resetSeries()` will be called which will prevent these issues.
Closing as similar to #655

**Comment by CatSizeVoyage** [comment]
Not sure if I've misunderstood but it doesn't look like this is fixed with 3.8.0 @junedchhipa ? If we call updateOptions with new options without series it still reactivates the deselected series in the legend and leaves the user with no way to actually reactivate that series.

[Codepen showing this](https://codepen.io/CatSizeVoyage/pen/NWKjQdp)

**Comment by SheriefAlaa** [comment]
Hi @junedchhipa, I am facing the exact same issue as @CatSizeVoyage pointed in their last CodePen. How would you get around this bug? any help would be appreciated.

Thanks!
