### ISSUE TITLE
Custom heatmap color for single datapoint

### ISSUE THREAD

**Issue by smilexu** [apexcharts/apexcharts.js#717]
**Is your feature request related to a problem? Please describe.**
In our project, we use heatmap to visualize latency data, in that case, most of latency data is low, few data has high value which means some unexpected situation happened. e.g. the value for 1-5s is 800, the value for 20-30s is 1.  In current heatmap implementation, the cell color is calculated by linear scale which we can not change, in this case, the cell with low value basically displayed as almost white, can not be seen easily.

**Describe the solution you'd like**
There are two solutions:
1. Support other color scale like pow scale.
2. Allow user to custom color for single datapoint, so we can display whatever color we want. There was a fix https://github.com/apexcharts/apexcharts.js/commit/b42bcef5c754b30b8cf978373af22ae064652040 , but this was only for the other charts besides heatmap.

The easiest way is option 2, since you already implemented for other charts.

**Comment by AndreasHerss** [comment]
I could really use this too, my usecase is a bit like the one above.
The range for every single datapoint's max ranges from 10 to above 100, and therefore the normal ranging doesn't make much sense in this case. as those with a max range of 10, would be colored too light :(

**Comment by Kulakoff1988** [comment]
I have the same request.

**Comment by lieyongchang** [comment]
I concur

**Comment by MrOli3000** [comment]
Same here! Would be great for heatmap!

**Comment by raannu** [comment]
I used single color heatmap chart but is shows multicolor
` 

import {
  ApexAxisChartSeries,
  ApexTitleSubtitle,
  ApexDataLabels,
  ApexChart
} from "ng-apexcharts";

export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  dataLabels: ApexDataLabels;
  title: ApexTitleSubtitle;
  colors: any;
};
@ViewChild("chart") chart: ChartComponent;
public chartOptionsapexmap: Partial<any>;
   constructor() {
    this.chartOptions = {
      series: [
        {
          name: "Metric1",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric2",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric3",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric4",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric5",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric6",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric7",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric8",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        },
        {
          name: "Metric9",
          data: this.generateData(18, {
            min: 0,
            max: 90
          })
        }
      ],
      chart: {
        height: 350,
        type: "heatmap"
      },
      dataLabels: {
        enabled: false
      },
      colors: ["#008FFB"],
      title: {
        text: "HeatMap Chart (Single color)"
      }
    };
  }`

**Comment by andrew-filippov** [comment]
I have found workaround for fixing issue caused by this heatmaps' behavior. Hopefully it will be useful for somebody...

The main idea is: as far as chart doesn't provide any options for defining color saturation range, we have to adjust values in data series. Short roadmap:
1. check input series - if min value is too low (or negative) we have to compress values range (compute another seria, based on the original): e.g. - we have values in the range 0..1000. Chart will appear greater values colorful, but small ones (~0..100) will be shown as white with white labels. So, let generate new seria, which will contains values in range 300..1000 (change every value in correct proportion! E.g. - zeroes become 300, 10 becomes 302, etc. but 1000 still 1000. You can implement any algorithm you wish). This allow us to show cells with low values colorful.
2. We have to provide value formatters for labels and tooltips which will show correct (original) values instead of synthetical ones. Formatters for chart are defined within "options" structure. Main idea: formatter function recieves input value as well as seria index and datapoint  index - so we just have to provide original seria via closure, and use indexes to pick and show original value.
