### ISSUE TITLE
Is it possible to disable unsafe inline style in ApexCharts ?

### ISSUE THREAD

**Issue by fungiboletus** [apexcharts/apexcharts.js#727]
Hei,

We use ApexCharts with Content Security Policy, and it seems that the option `style-src 'self' 'unsafe-inline'`.

If not the following error happens and the charts layouts are broken.

```
Refused to apply inline style because it violates the following Content Security Policy directive
```

Is it possible to use ApexCharts without unsafe inline styles ?

**Comment by junedchhipa** [comment]
There are a lot of places where styles are applied directly to elements.
For eg., calculating the chart's width/height based on available space, tooltip's position, etc.
It's not possible to move those inline styles to an external stylesheet, hence you may need to tweak some other ways to make it work with CSP, Sorry.

**Comment by spotman** [comment]
@junedchhipa the right way to pass CSP rules is to set CSS styles via JS (DOM) and not via HTML properties in template. Other charting libraries implemented this already so it can be done in ApexCharts too ;) This issue blocks using of your beautiful library in secure environments with strict CSP rules.

**Comment by junedchhipa** [comment]
At some places, inline styles are set using
```
elWrap.style.width = gl.svgWidth + 'px'
```
Is there any other way?

**Comment by spotman** [comment]
@junedchhipa AFAIK this is OK until you are setting HTML attribute `style` to some string like
`el.style = "width: 150px"`

**Comment by junedchhipa** [comment]
Nope, setting the element's style as HTML attribute is not done anywhere.

**Comment by spotman** [comment]
@junedchhipa hmm, I need some time to investigate this.

The simplest way to debug CSP is to add HTML `meta` tag
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'">`
so you'll see all possible errors for the most strict CSP rule.

**Comment by junedchhipa** [comment]
That was really helpful.
Thanks for the hint.

**Comment by spotman** [comment]
@junedchhipa you are welcome :)

I see errors generated by `function styleInject()`, it is injecting `<style>` tag into HTML. This is not allowed in CSP and can be replaced with direct import in ES2015 module. Doing this will help modern bundlers (webpack, etc) to split JS and CSS into seaprate files.

**Comment by spotman** [comment]
@junedchhipa may I help you with this issue? I really like your lib but this issue blocks me for using ApexCharts in my project.

**Comment by junedchhipa** [comment]
Sure.
A Pull Request is always welcome.

**Comment by spotman** [comment]
@junedchhipa fixed CSP issues in #953 You are welcome to make any changes in my fork.

**Comment by junedchhipa** [comment]
Thanks for the contribution @spotman 
All looks good.

**Comment by blueeDeveloper** [comment]
@junedchhipa - I am getting below error on my console. i have the latest version of apexcharts. 

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.apple.com". Either the 'unsafe-inline' keyword, a hash ('sha256-We76yQ6BbUqy3OL7pB4AiChSOtAH/BdDsZ0Z+MzXvD0='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Is there a way to get rid of this error. Due to this error, the styling of the stacked bar chart is a little messed up.

**Comment by egaga** [comment]
When calling render, I think I'm getting the following error at this location: https://github.com/apexcharts/apexcharts.js/blob/7a7f6cc1bc389c3f568fd9c47d4e9d194898f5cd/src/apexcharts.js#L93

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('...some hash...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by redwingjusticework** [comment]
push please help fixing csp issue

apexcharts.js:14533 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-r6YXf0FH0c0za5mvk1odENR+z4qTbdvjkTiTyOeKU30='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

apexcharts.js:33622 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-SSGCrClQA5HDwURccGOBm8CCOfMt1gmANv5KkeZERXs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by Ctere1** [comment]
https://apexcharts.com/docs/options/chart/nonce/

### Explanation: Configuring ApexCharts with a Nonce for CSP Compliance

To ensure **ApexCharts** works seamlessly with a **Content Security Policy (CSP)** that disallows inline styles or scripts, you need to set a `nonce` value in the chart options. This `nonce` will be used by ApexCharts when applying styles or scripts dynamically.

#### Why This Is Important
Modern security policies often include CSP headers to prevent XSS attacks. However, libraries like ApexCharts generate inline styles and scripts that trigger CSP violations unless explicitly permitted. By using a `nonce`, we can allow these inline styles and scripts without compromising security.

---

### How to Configure ApexCharts with a Nonce

In your **ApexCharts configuration**, specify the `nonce` under the `chart` object:

```javascript
const chartOptions = {
  chart: {
    id: 'example-chart',
    nonce: '123456',  // Set your nonce value here
    toolbar: {
      show: false,
    },
    zoom: {
      enabled: false,
    },
    animations: {
      enabled: true,
      speed: 360,
      animateGradually: {
        enabled: false,
        delay: 120,
      },
      dynamicAnimation: {
        enabled: false,
        speed: 360,
      },
    },
    foreColor: theme.palette.text.disabled,
    fontFamily: theme.typography.fontFamily,
  },
  series: [
    {
      name: 'Data Series 1',
      data: [10, 20, 30, 40],
    },
  ],
  xaxis: {
    categories: ['Jan', 'Feb', 'Mar', 'Apr'],
  },
};

**Comment by redwingjusticework** [comment]
> > When calling render, I think I'm getting the following error at this location:
> > [apexcharts.js/src/apexcharts.js](https://github.com/apexcharts/apexcharts.js/blob/7a7f6cc1bc389c3f568fd9c47d4e9d194898f5cd/src/apexcharts.js#L93)
> > Line 93 in [7a7f6cc](/apexcharts/apexcharts.js/commit/7a7f6cc1bc389c3f568fd9c47d4e9d194898f5cd)
> > doc.head.appendChild(this.css)
> > > Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('...some hash...'), or a nonce ('nonce-...') is required to enable inline execution.
> 
> I got this error as well, my solution was to try to build and remove "dynamic" styles and stop inlining the css. I tried it locally with a fork of apexcharts.
> 
> [@junedchhipa](https://github.com/junedchhipa) do the styles hvae to be inlined? Isnt it possible to ask people to bring the css as a seperate file? that would fix CSP issues

me too i got this error also. same opinion that bring css as a seperate file is welcome apexchart.css very good framework but cannot use because of CSP issues sigh

**Comment by OakyLabs** [comment]
Just fyi, got it working locally once more and was able to push it to production and pass the strictest csp policy lines by, like i said, stopping javascript to set styles, but to import the stylesheet file in the html.
By making the necessary changes (moving the `legend` styles to the main css file, and having the shadow dom import the same link with the stylesheets, everything works

**Comment by Gnanarajk** [comment]
@OakyLabs 
I'm using angular v18 and use apexchart, can you pls tell me the steps on how to implement the importing styles into html (is that index.html you mean)., pls explain

**Comment by OakyLabs** [comment]
@Gnanarajk  you actually have to make changes to the node_modules then. Do a patch of the node_modules.

Then you need to change the .style = "". In my case, the issue was in LegendStyles. Instead of having the css inlined, i put it in the bundled apexcharts.css. That alone was enough to fix it.

Then , theres also something in the main.js, if im not imstaken, that also imports `apexCss` and does: and creates a stylesheet and appends the css property. again, remove that line and import the apexcharts.css
