### ISSUE TITLE
get coordinate on click on line chart

### ISSUE THREAD

**Issue by shalma29** [apexcharts/apexcharts.js#769]
Hi.
I made a line chart with Apex Chart, and i can't find any solution for my question.

I would like to set my chart a little interactive, ie, i would like the user to click on the chart (whatever they want), and it draws an annotation.

I know how to draw an annotation with addYaxisAnnotation, but i can't take the y value from a click on the chart.

Any idea ?

**Comment by junedchhipa** [comment]
The `chart.events.click` will return normal event attributes, not the x/y coordinates.
Hence, it's not possible to directly get the y values from a click event.

There is another event called `chart.events.dataPointSelection` where the user has to click on the marker. Clicking on the marker will give you the y values or the value selected. This way it will be possible to draw annotation.

**Comment by Howiezhu** [comment]
Is there a way to indirectly derive the Y coordinate that the user clicked on? In JAVA there are some way of transforming chart x, y to Plot X and Y. I am just wondering if you have ever encountered or a way to actually retrieve Y point the user clicked on? The reason Is I want a way for user to define a point which they may want to fix the chart data? or liek shlma29 said add an annotation.
