### ISSUE TITLE
Demo: zoomable-timeseries `ReferenceError: dataSeries is not defined`

### ISSUE THREAD

**Issue by marclundgren** [apexcharts/apexcharts.js#831]
## Live Demo
https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/

## Codepen
https://codepen.io/marclundgren/pen/jgZmQj

## Explanation
Try to run the demo in codepen or your own server. You'll see `ReferenceError: dataSeries is not defined`

The demo should work, and be free of type errors. Further, there is a `spikes` array that's defined but never used. This seems to affect multiple line chart demos.

**Comment by groubis** [comment]
Hi @marclundgren,

I really believe that you are just trolling but i will answer:

1. The dataSeries array is not included in the demo, because it's huge.
2. You can easily find the dataSeries array in the demo page through chrome devtools.
3. Your pen has several issues (wrong id of div used, wrong and commented format of dataSeries array.

Anyway, i created [this pen](https://codepen.io/george-roubis/pen/yLBeEjQ) for you to have a look...

Thanks!

**Comment by flowck** [comment]
Thank you @groubis for having the patience to share the code pen.
