### ISSUE TITLE
Repeated y-axis labels for series with max value of 1

### ISSUE THREAD

**Issue by drummad** [apexcharts/apexcharts.js#838]
## Codepen

https://codepen.io/Drummad/pen/ymRdBX

## Explanation

When the highest value in the series is 1 the y-axis labels are displayed with repeated 0's and 1's. I would expect just to see a single label each for 0 and 1.

If the y-axis formatter function is removed then decimal values "0.3,  0.6,  0.9,  1.2" are displayed which the formatter is then clearly rounding to the integer values. It seems that the tickAmount isn't being adjusted correctly as it would be for other values below the default of 6. For example, setting a value in any series to 2 seems to cause the tickAmount to be adjusted.

Thanks again for this great library.

**Comment by junedchhipa** [comment]
If you don't want repeated y-axis labels for small values, you should reduce the tickAmount (tick-amount is not automatically set because it causes a lot of issues for other use-cases).

After trying several ways to make it work automatically, I have left it to the user to set it.
Hence, you can check what is your highest value in advance and based on that, change the tickAmount value to avoid repetition.

**Comment by drummad** [comment]
Thank you for the reply. Implementing this logic manually on each chart is going to be a pain, especially as filters on the page update the charts with series of varying sizes. It's definitely not an ideal solution in terms of implementation and code maintenance going forward but I appreciate it's the only option.
