### ISSUE TITLE
stacked and grouped to create waterfall

### ISSUE THREAD

**Issue by cwiese** [apexcharts/apexcharts.js#847]
Can you currently create multiple series and have one series grouped ... so I can create a waterfall chart.  The Stacking comes from make this send bar in each year have an opacity 0 segment to make it rise above the zero line.    I considered a candlestick chart but that chart does not allow multiple series (3 bars per year) ...

![image](https://user-images.githubusercontent.com/178527/63293161-66ac6300-c295-11e9-8e98-108f4af68846.png)

**Comment by junedchhipa** [comment]
Sorry, that's not possible currently.

**Comment by junedchhipa** [comment]
You may use the range column charts to create something similar to what you've described.
https://apexcharts.com/javascript-chart-demos/column-charts/range-column-chart/

**Comment by junedchhipa** [comment]
Revisiting this: there is a first class waterfall type now, so no spacer segments and no precomputed pairs. You give the steps and the running totals are worked out for you.

```js
{
  chart: { type: 'waterfall' },
  series: [{
    name: 'Cash flow',
    data: [
      { x: 'Net revenue',        y: 8786000 },
      { x: 'Cost of sales',      y: -2786000 },
      { x: 'Gross profit',       isSubtotal: true },
      { x: 'Operating expenses', y: -1786000 },
      { x: 'Income from equity', y: 1465000 },
      { x: 'Operating income',   isTotal: true },
    ],
  }],
}
```

A row with `y` is a step and moves the running total by it. `isSubtotal` draws the sum of the steps since the previous total bar and `isTotal` draws the sum from zero, so you never state either number yourself. Increases, decreases and totals are coloured apart by default and the dashed connectors between bars are drawn for you; `plotOptions.waterfall` carries the colours and the connector styling, and `plotOptions.bar.horizontal: true` gives the horizontal form.

This lands in 7.1.0.
