### ISSUE TITLE
Everything rendered after an Apex pie/donut will disappear if animations are disabled

### ISSUE THREAD

**Issue by msageryd** [apexcharts/apexcharts.js#885]
## Code

```html
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

<div id="chart"/>

<script>
    const options = {
        chart: {
            type: 'pie',
            width: 400,
            animations: {
                enabled: false
            }
        },
        series: [1,2,3],
    }
    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();
</script>

This text will not be rendered if animations are disabled!!

```

## Explanation

If animations are disabled (or set to speed=0), everything after the chart div will disappear. The above code demonstrates this. The text after the chart div will be visible for a very short period (flashes).

The same code with animations.speed=10 will work.

**Comment by kevinhinterlong** [comment]
Here's a [link](https://jsfiddle.net/xcgy6tp4/) to run the code you wrote, but the issue here is with `<div id="chart"/>` a self closing div is not valid and ends up [parsing](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus) what you expect to be sibling elements into children elements. Changing this to `<div id="chart"></div>` solves this

**Comment by msageryd** [comment]
> Here's a [link](https://jsfiddle.net/xcgy6tp4/) to run the code you wrote, but the issue here is with `<div id="chart"/>` a self closing div is not valid and ends up [parsing](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus) what you expect to be sibling elements into children elements. Changing this to `<div id="chart"></div>` solves this

Thanks Kevin. I didn't realize that this issue got answered.
I don't do much html, so I didn't know this. Is it generally invalid with self-closing tags, or does it only relate to div?

**Comment by kevinhinterlong** [comment]
@msageryd there's a note in the section I linked to
> (Self-closing tags don't exist in HTML.) It is also allowed for void elements, but doesn't have any effect in this case.

So if you were to use a [void element](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) it would parse how you expected where they are siblings instead of children elements. Everything else (`div`, `span`, etc) would end up in the same situation.

Here's an [example](https://jsfiddle.net/o364aLnq/) using `hr` (since it doesn't expect a closing tag, the ending ` />` has no effect and it renders the next elements as siblings)
