### ISSUE TITLE
Zooming in on x-axis range annotations makes them disappear

### ISSUE THREAD

**Issue by x42y** [apexcharts/apexcharts.js#917]
https://apexcharts.com/javascript-chart-demos/line-charts/line-chart-annotations/

Zooming in on the x-axis range annotation makes it disappear.

**Comment by boxbinary** [comment]
Hi there, found this while researching the same issue. If I scroll or zoom to where the minimum x axis is now greater than the first dynamically added annotation, all dynamically added ones disappear.

**Comment by boxbinary** [comment]
It might possibly be due to this exception that is being thrown when zooming: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

It appears the query for finding the elements to draw the background of the annotation fails to return any elements, but then the function to add a background runs anyway without having checked for null. I wonder if this exception is then killing the entire process of drawing any annotations.

**Comment by JithinW** [comment]
Any Fix for this problem?
