### ISSUE TITLE
Mixed charts, inconsistent behaviour, offset on X axis

### ISSUE THREAD

**Issue by gsabetta** [apexcharts/apexcharts.js#946]
## Codepen
https://codepen.io/gerardosabetta/pen/wvwLpPo
https://imgur.com/a/PJEVSWI

## Explanation
Inconsistent behavior, maybe this is a feature but it confused me for a while.
When you're working with mixed charts (I just tested columns and lines) you have 2 behaviors.

1- You start with a cropped column, the line chart marker is well aligned with the categories on the bottom and everything works as expected (I think this is the best thing to do, it makes sense)

2- You see a full column but there's a weird offset on the categories

 
- What is the behavior you expect?
I expect the output to be consistent
- What is happening instead?
It is not consistent
- What error message are you getting?

**Comment by gsabetta** [comment]
I modified the title because this is not caused strictly by having that parameter set. It also happens if you declare your column series before your line series

**Comment by junedchhipa** [comment]
If you don't specify the xaxis type and any categories, the resulting xaxis is different for columns and lines.
The weird offset on the column is because the xaxis gets converted in numeric.

To get consistent behavior, specify the xaxis type and/or categories.

```javascript
xaxis: {
    type: 'category',
    categories: [1, 2, 3, 4, 5]
}
```

The above addition will produce the same results regardless if the line is drawn before or after the column.
