### ISSUE TITLE
Allow for auto adjustment of x-axis labels for every type of data series

### ISSUE THREAD

**Issue by neslinesli93** [apexcharts/apexcharts.js#976]
Hi!

First of all, thanks for the project! I was looking for a ChartJS alternative with cool React integrations, and your project seems like a really good fit (: 

I was playing with the demos and I tried pushing a couple hundred datapoints on a line chart, with the default `category` serie, and I noticed that many of the labels in x-axis were overlapping. From the docs, I think what happens is that only for `datetime` series you get auto-adjustment/interpolation of the labels shown in the x-axis, while for the others you can't. Maybe you can do something with `numeric` series, using `tickAmount`, but I'm not sue...

So, is there a way to autoadjust the amount of labels shown in the x-axis, when dealing with normal line series charts?

Thanks, and keep it up with the great work you've been doing

**Comment by nhuchon** [comment]
Hi! 
I would really like this feature to be available! 

When I use the format `series: {data:[x,y]}` like in this pen,https://codepen.io/nhuchon/pen/oNNeroJ , I can use the `tickAmount`  property. The problem is that I can't use this format when my data are strings.  (like in this pen: https://codepen.io/nhuchon/pen/dyyzBvQ).

There is another way to transcript data, like in this codepen : https://codepen.io/nhuchon/pen/MWWvMzr , but you can see that the `tickAmount` is not display like wanted. So currently, there is now way to use the `tickAmount` for data with string abscissa.

I would really need a way to use this, cause when you have a large amount of data, the labels just overwrite themself and are just unreadable

Thanks for your work

**Comment by guruprasadreddydev** [comment]
ApexCharts automatically adjusts the x-axis based on the data range, and if your data has only a 10-second interval, it's challenging to force it to display hourly intervals on the x-axis.

**Comment by guruprasadreddydev** [comment]
i want show hours by default
